services:
  - type: web
    name: monitraq
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
